# Generated by Django 3.1.7 on 2021-05-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_streamingservice_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('hours_worked_monday', models.FloatField(default=0)),
                ('hours_worked_tuesday', models.FloatField(default=0)),
                ('hours_worked_wednesday', models.FloatField(default=0)),
                ('hours_worked_thursday', models.FloatField(default=0)),
                ('hours_worked_friday', models.FloatField(default=0)),
                ('hours_worked_saturday', models.FloatField(default=0)),
                ('hours_worked_sunday', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='calendar_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.calendar'),
        ),
    ]
